### ISSUE TITLE
Generate longer captchas

### ISSUE THREAD

**Issue by vipersec** [trekjs/captcha#3]
Every captcha that is generated is 5 characters length.

If I want to generate an 8-length captcha using the code below: 
`const { token, buffer } = captcha(8)`

A 5-length captcha is generated instead.

**Comment by fundon** [comment]
Ok, I like this feature.

**Comment by fundon** [comment]
@vipersec See https://github.com/trekjs/captcha/tree/pure-js.

I had refactored it to pure JS. We can do more.

**Comment by mtsee** [comment]
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at babelWatchLoader (D:\DT\H5DS3.0\build\node_modules\.2.0.7@babel-watch\run
ner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (D:\DT\H5DS3.0\bu
ild\node_modules\.2.0.7@babel-watch\runner.js:61:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\DT\H5DS3.0\build\router.js:13:19)
    at Module._compile (module.js:413:34)

**Comment by fundon** [comment]
@mtsee Which Node.js version you are using?

**Comment by mtsee** [comment]
v6.2.0

**Comment by fundon** [comment]
`async/await` require v8+.
